name: Flash-Md-V3 Deployment

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows manual start
  schedule:
    - cron: '0 */4 * * *' # Restarts every 4 hours to bypass timeouts

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Dependencies
        run: |
          npm install
          # Some bots require extra packages like ffmpeg
          sudo apt-get install -y ffmpeg

      - name: Run Flash-Md-V3
        timeout-minutes: 350 # Stops just before the 6-hour GitHub limit
        run: npm start
        env:
          SESSION_ID: ${{ secrets.SESSION_ID }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          OWNER_NUMBER: ${{ secrets.OWNER_NUMBER }}
          PREFIX: ${{ secrets.PREFIX }}
          MODE: ${{ secrets.MODE }}

